version: 2
jobs:
  build:
    docker:
      - image: fmidev/rpmbuild:el7
        entrypoint: bash
    steps:
      - checkout
      - run:
          name: Create local repo
          command: createrepo /home/rpmbuild/rpmbuild/RPMS/x86_64
      - run:
          name: Install dependencies
          command: sudo yum-builddep -y *.spec 
      - run:
          name: Make rpm
          command: make rpm
      - run:
          name: Move artifacts
          command: sudo cp -av /home/rpmbuild/rpmbuild/RPMS /
      - store_artifacts:
          path: /RPMS
