version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker run -h rpmbuild-el7.fmi.fi -v $HOME/project:/home/rpmbuild/rpmbuild/SOURCES/$CIRCLE_PROJECT_REPONAME --rm fmidev/rpmbuild:el7 $CIRCLE_PROJECT_REPONAME 
