version: 2
jobs:
  build:
    docker:
      - image: fmidev/rpmbuild:el7
      - entrypoint: bash
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo yum-builddep -y *.spec 
      - run:
          name: Make rpm
          command: make rpm
